export const mockClients = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "123-456-7890",
    company: "Acme Corp",
    address: "123 Main St, Springfield, IL 62704",
    industry: "Manufacturing",
    website: "https://www.acmecorp.com",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "987-654-3210",
    company: "Globex Inc",
    address: "456 Elm St, Metropolis, NY 10001",
    industry: "Technology",
    website: "https://www.globex.com",
  },
  {
    id: 3,
    name: "Robert Johnson",
    email: "robert.johnson@example.com",
    phone: "555-123-4567",
    company: "Soylent Corp",
    address: "789 Oak St, Gotham, NJ 07097",
    industry: "Food & Beverage",
    website: "https://www.soylent.com",
  },
  {
    id: 4,
    name: "Emily Davis",
    email: "emily.davis@example.com",
    phone: "444-555-6666",
    company: "Initech",
    address: "321 Pine St, Smallville, KS 67524",
    industry: "Software",
    website: "https://www.initech.com",
  },
  {
    id: 5,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    phone: "222-333-4444",
    company: "Umbrella Corp",
    address: "654 Cedar St, Raccoon City, PA 15022",
    industry: "Pharmaceuticals",
    website: "https://www.umbrella.com",
  },
  {
    id: 6,
    name: "Sarah Wilson",
    email: "sarah.wilson@example.com",
    phone: "777-888-9999",
    company: "Hooli",
    address: "987 Birch St, Palo Alto, CA 94301",
    industry: "Technology",
    website: "https://www.hooli.com",
  },
  {
    id: 7,
    name: "David Martinez",
    email: "david.martinez@example.com",
    phone: "111-222-3333",
    company: "Stark Industries",
    address: "159 Maple St, Long Island City, NY 11101",
    industry: "Defense",
    website: "https://www.starkindustries.com",
  },
  {
    id: 8,
    name: "Laura Garcia",
    email: "laura.garcia@example.com",
    phone: "666-777-8888",
    company: "Wayne Enterprises",
    address: "753 Walnut St, Gotham, NJ 07097",
    industry: "Conglomerate",
    website: "https://www.wayneenterprises.com",
  },
  {
    id: 9,
    name: "James Anderson",
    email: "james.anderson@example.com",
    phone: "333-444-5555",
    company: "Massive Dynamic",
    address: "852 Cherry St, New York, NY 10002",
    industry: "Biotechnology",
    website: "https://www.massivedynamic.com",
  },
  {
    id: 10,
    name: "Patricia Thomas",
    email: "patricia.thomas@example.com",
    phone: "999-000-1111",
    company: "Wonka Industries",
    address: "951 Poplar St, Tulsa, OK 74104",
    industry: "Confectionery",
    website: "https://www.wonkaindustries.com",
  },
  {
    id: 11,
    name: "Charles Taylor",
    email: "charles.taylor@example.com",
    phone: "888-999-0000",
    company: "Oscorp",
    address: "147 Aspen St, Queens, NY 11101",
    industry: "Biotechnology",
    website: "https://www.oscorp.com",
  },
  {
    id: 12,
    name: "Linda Moore",
    email: "linda.moore@example.com",
    phone: "555-666-7777",
    company: "Tyrell Corporation",
    address: "258 Spruce St, Los Angeles, CA 90001",
    industry: "Robotics",
    website: "https://www.tyrell.com",
  },
  {
    id: 13,
    name: "Thomas Jackson",
    email: "thomas.jackson@example.com",
    phone: "444-333-2222",
    company: "Cyberdyne Systems",
    address: "369 Fir St, San Francisco, CA 94102",
    industry: "Artificial Intelligence",
    website: "https://www.cyberdyne.com",
  },
  {
    id: 14,
    name: "Barbara White",
    email: "barbara.white@example.com",
    phone: "222-111-0000",
    company: "Wonka Candy",
    address: "147 Willow St, Chicago, IL 60601",
    industry: "Confectionery",
    website: "https://www.wonkacandy.com",
  },
  {
    id: 15,
    name: "Daniel Harris",
    email: "daniel.harris@example.com",
    phone: "333-222-1111",
    company: "Vandelay Industries",
    address: "258 Cypress St, Miami, FL 33101",
    industry: "Import/Export",
    website: "https://www.vandelay.com",
  },
  {
    id: 16,
    name: "Jennifer Martin",
    email: "jennifer.martin@example.com",
    phone: "777-666-5555",
    company: "Pied Piper",
    address: "369 Palm St, Silicon Valley, CA 94016",
    industry: "Technology",
    website: "https://www.piedpiper.com",
  },
  {
    id: 17,
    name: "Matthew Thompson",
    email: "matthew.thompson@example.com",
    phone: "111-333-5555",
    company: "Gringotts",
    address: "123 Dragon St, London, UK SW1A 1AA",
    industry: "Finance",
    website: "https://www.gringotts.com",
  },
  {
    id: 18,
    name: "Elizabeth Garcia",
    email: "elizabeth.garcia@example.com",
    phone: "444-666-8888",
    company: "Fabrikam",
    address: "456 Unicorn St, Seattle, WA 98101",
    industry: "Manufacturing",
    website: "https://www.fabrikam.com",
  },
  {
    id: 19,
    name: "Christopher Martinez",
    email: "christopher.martinez@example.com",
    phone: "999-888-7777",
    company: "Contoso",
    address: "789 Pegasus St, Boston, MA 02108",
    industry: "Technology",
    website: "https://www.contoso.com",
  },
  {
    id: 20,
    name: "Susan Robinson",
    email: "susan.robinson@example.com",
    phone: "666-555-4444",
    company: "Aperture Science",
    address: "321 Portal St, Colorado Springs, CO 80903",
    industry: "Scientific Research",
    website: "https://www.aperturescience.com",
  },
  {
    id: 21,
    name: "Kevin Clark",
    email: "kevin.clark@example.com",
    phone: "555-444-3333",
    company: "Rich Industries",
    address: "654 Quantum St, Austin, TX 73301",
    industry: "Engineering",
    website: "https://www.richindustries.com",
  },
  {
    id: 22,
    name: "Karen Rodriguez",
    email: "karen.rodriguez@example.com",
    phone: "222-444-6666",
    company: "Stark Enterprises",
    address: "987 Infinity St, New York, NY 10003",
    industry: "Defense",
    website: "https://www.starkenterprises.com",
  },
  {
    id: 23,
    name: "Brian Lewis",
    email: "brian.lewis@example.com",
    phone: "333-555-7777",
    company: "LexCorp",
    address: "159 Krypton St, Metropolis, NY 10004",
    industry: "Conglomerate",
    website: "https://www.lexcorp.com",
  },
  {
    id: 24,
    name: "Nancy Lee",
    email: "nancy.lee@example.com",
    phone: "888-222-1111",
    company: "Wayne Tech",
    address: "753 Gotham St, Gotham, NJ 07098",
    industry: "Technology",
    website: "https://www.wayne-tech.com",
  },
  {
    id: 25,
    name: "George Walker",
    email: "george.walker@example.com",
    phone: "444-777-9999",
    company: "Oscorp Industries",
    address: "852 Spider St, Queens, NY 11102",
    industry: "Biotechnology",
    website: "https://www.oscorpindustries.com",
  },
];

export const mockDonations = [
  // Donations for Client ID 1
  {
    id: 1,
    clientId: 1,
    date: "2024-01-05",
    amount: 100,
    type: "One-time",
    method: "Credit Card",
    category: "General",
  },
  {
    id: 2,
    clientId: 1,
    date: "2024-02-15",
    amount: 150,
    type: "Monthly",
    method: "Bank Transfer",
    category: "Research",
  },
  {
    id: 3,
    clientId: 1,
    date: "2024-03-10",
    amount: 200,
    type: "One-time",
    method: "PayPal",
    category: "Infrastructure",
  },
  {
    id: 4,
    clientId: 1,
    date: "2024-04-20",
    amount: 250,
    type: "Monthly",
    method: "Credit Card",
    category: "Events",
  },
  {
    id: 5,
    clientId: 1,
    date: "2024-05-25",
    amount: 300,
    type: "Yearly",
    method: "Bank Transfer",
    category: "General",
  },

  // Donations for Client ID 2
  {
    id: 6,
    clientId: 2,
    date: "2024-01-12",
    amount: 200,
    type: "One-time",
    method: "Credit Card",
    category: "General",
  },
  {
    id: 7,
    clientId: 2,
    date: "2024-02-18",
    amount: 250,
    type: "Monthly",
    method: "Bank Transfer",
    category: "Research",
  },
  {
    id: 8,
    clientId: 2,
    date: "2024-03-22",
    amount: 300,
    type: "One-time",
    method: "PayPal",
    category: "Infrastructure",
  },
  {
    id: 9,
    clientId: 2,
    date: "2024-04-30",
    amount: 350,
    type: "Monthly",
    method: "Credit Card",
    category: "Events",
  },
  {
    id: 10,
    clientId: 2,
    date: "2024-05-15",
    amount: 400,
    type: "Yearly",
    method: "Bank Transfer",
    category: "General",
  },

  // Donations for Client ID 3
  {
    id: 11,
    clientId: 3,
    date: "2024-01-08",
    amount: 150,
    type: "One-time",
    method: "PayPal",
    category: "Events",
  },
  {
    id: 12,
    clientId: 3,
    date: "2024-02-14",
    amount: 200,
    type: "Monthly",
    method: "Credit Card",
    category: "General",
  },
  {
    id: 13,
    clientId: 3,
    date: "2024-03-19",
    amount: 250,
    type: "One-time",
    method: "Bank Transfer",
    category: "Research",
  },
  {
    id: 14,
    clientId: 3,
    date: "2024-04-25",
    amount: 300,
    type: "Monthly",
    method: "PayPal",
    category: "Infrastructure",
  },
  {
    id: 15,
    clientId: 3,
    date: "2024-05-30",
    amount: 350,
    type: "Yearly",
    method: "Credit Card",
    category: "General",
  },

  // Donations for Client ID 4
  {
    id: 16,
    clientId: 4,
    date: "2024-01-10",
    amount: 500,
    type: "Yearly",
    method: "Bank Transfer",
    category: "Infrastructure",
  },
  {
    id: 17,
    clientId: 4,
    date: "2024-02-20",
    amount: 100,
    type: "One-time",
    method: "PayPal",
    category: "Research",
  },
  {
    id: 18,
    clientId: 4,
    date: "2024-03-05",
    amount: 150,
    type: "Monthly",
    method: "Credit Card",
    category: "Events",
  },
  {
    id: 19,
    clientId: 4,
    date: "2024-04-15",
    amount: 200,
    type: "One-time",
    method: "Bank Transfer",
    category: "General",
  },
  {
    id: 20,
    clientId: 4,
    date: "2024-05-25",
    amount: 250,
    type: "Monthly",
    method: "PayPal",
    category: "Research",
  },

  // Donations for Client ID 5
  {
    id: 21,
    clientId: 5,
    date: "2024-01-18",
    amount: 250,
    type: "Monthly",
    method: "Credit Card",
    category: "General",
  },
  {
    id: 22,
    clientId: 5,
    date: "2024-02-28",
    amount: 350,
    type: "One-time",
    method: "Bank Transfer",
    category: "Events",
  },
  {
    id: 23,
    clientId: 5,
    date: "2024-03-12",
    amount: 400,
    type: "Monthly",
    method: "PayPal",
    category: "Infrastructure",
  },
  {
    id: 24,
    clientId: 5,
    date: "2024-04-22",
    amount: 450,
    type: "One-time",
    method: "Credit Card",
    category: "Research",
  },
  {
    id: 25,
    clientId: 5,
    date: "2024-05-18",
    amount: 500,
    type: "Yearly",
    method: "Bank Transfer",
    category: "General",
  },

  // Donations for Client ID 6
  {
    id: 26,
    clientId: 6,
    date: "2024-01-07",
    amount: 300,
    type: "Monthly",
    method: "PayPal",
    category: "Research",
  },
  {
    id: 27,
    clientId: 6,
    date: "2024-02-17",
    amount: 600,
    type: "Yearly",
    method: "Credit Card",
    category: "Infrastructure",
  },
  {
    id: 28,
    clientId: 6,
    date: "2024-03-27",
    amount: 350,
    type: "One-time",
    method: "Bank Transfer",
    category: "Events",
  },
  {
    id: 29,
    clientId: 6,
    date: "2024-04-10",
    amount: 400,
    type: "Monthly",
    method: "PayPal",
    category: "General",
  },
  {
    id: 30,
    clientId: 6,
    date: "2024-05-20",
    amount: 450,
    type: "One-time",
    method: "Credit Card",
    category: "Research",
  },

  // Donations for Client ID 7
  {
    id: 31,
    clientId: 7,
    date: "2024-01-14",
    amount: 200,
    type: "One-time",
    method: "Bank Transfer",
    category: "Events",
  },
  {
    id: 32,
    clientId: 7,
    date: "2024-02-24",
    amount: 450,
    type: "Monthly",
    method: "PayPal",
    category: "General",
  },
  {
    id: 33,
    clientId: 7,
    date: "2024-03-08",
    amount: 500,
    type: "One-time",
    method: "Credit Card",
    category: "Research",
  },
  {
    id: 34,
    clientId: 7,
    date: "2024-04-18",
    amount: 550,
    type: "Monthly",
    method: "Bank Transfer",
    category: "Infrastructure",
  },
  {
    id: 35,
    clientId: 7,
    date: "2024-05-28",
    amount: 600,
    type: "Yearly",
    method: "PayPal",
    category: "General",
  },

  // Donations for Client ID 8
  {
    id: 36,
    clientId: 8,
    date: "2024-01-09",
    amount: 500,
    type: "Yearly",
    method: "Credit Card",
    category: "Research",
  },
  {
    id: 37,
    clientId: 8,
    date: "2024-02-19",
    amount: 150,
    type: "One-time",
    method: "Bank Transfer",
    category: "Infrastructure",
  },
  {
    id: 38,
    clientId: 8,
    date: "2024-03-29",
    amount: 200,
    type: "Monthly",
    method: "PayPal",
    category: "Events",
  },
  {
    id: 39,
    clientId: 8,
    date: "2024-04-11",
    amount: 250,
    type: "One-time",
    method: "Credit Card",
    category: "General",
  },
  {
    id: 40,
    clientId: 8,
    date: "2024-05-21",
    amount: 300,
    type: "Monthly",
    method: "Bank Transfer",
    category: "Research",
  },

  // Donations for Client ID 9
  {
    id: 41,
    clientId: 9,
    date: "2024-01-16",
    amount: 300,
    type: "Monthly",
    method: "PayPal",
    category: "Events",
  },
  {
    id: 42,
    clientId: 9,
    date: "2024-02-26",
    amount: 400,
    type: "One-time",
    method: "Credit Card",
    category: "General",
  },
  {
    id: 43,
    clientId: 9,
    date: "2024-03-10",
    amount: 450,
    type: "Monthly",
    method: "Bank Transfer",
    category: "Research",
  },
  {
    id: 44,
    clientId: 9,
    date: "2024-04-20",
    amount: 500,
    type: "One-time",
    method: "PayPal",
    category: "Infrastructure",
  },
  {
    id: 45,
    clientId: 9,
    date: "2024-05-30",
    amount: 550,
    type: "Yearly",
    method: "Credit Card",
    category: "General",
  },

  // Donations for Client ID 10
  {
    id: 46,
    clientId: 10,
    date: "2024-01-03",
    amount: 250,
    type: "One-time",
    method: "Bank Transfer",
    category: "Research",
  },
  {
    id: 47,
    clientId: 10,
    date: "2024-02-13",
    amount: 500,
    type: "Yearly",
    method: "PayPal",
    category: "Infrastructure",
  },
  {
    id: 48,
    clientId: 10,
    date: "2024-03-23",
    amount: 350,
    type: "Monthly",
    method: "Credit Card",
    category: "Events",
  },
  {
    id: 49,
    clientId: 10,
    date: "2024-04-07",
    amount: 400,
    type: "One-time",
    method: "Bank Transfer",
    category: "General",
  },
  {
    id: 50,
    clientId: 10,
    date: "2024-05-17",
    amount: 450,
    type: "Monthly",
    method: "PayPal",
    category: "Research",
  },

  // Donations for Client ID 11
  {
    id: 51,
    clientId: 11,
    date: "2024-01-07",
    amount: 350,
    type: "Monthly",
    method: "Credit Card",
    category: "General",
  },
  {
    id: 52,
    clientId: 11,
    date: "2024-02-17",
    amount: 200,
    type: "One-time",
    method: "Bank Transfer",
    category: "Events",
  },
  {
    id: 53,
    clientId: 11,
    date: "2024-03-27",
    amount: 250,
    type: "Monthly",
    method: "PayPal",
    category: "Research",
  },
  {
    id: 54,
    clientId: 11,
    date: "2024-04-11",
    amount: 300,
    type: "One-time",
    method: "Credit Card",
    category: "Infrastructure",
  },
  {
    id: 55,
    clientId: 11,
    date: "2024-05-21",
    amount: 350,
    type: "Monthly",
    method: "Bank Transfer",
    category: "General",
  },

  // Donations for Client ID 12
  {
    id: 56,
    clientId: 12,
    date: "2024-01-14",
    amount: 400,
    type: "Monthly",
    method: "PayPal",
    category: "Research",
  },
  {
    id: 57,
    clientId: 12,
    date: "2024-02-24",
    amount: 600,
    type: "Yearly",
    method: "Credit Card",
    category: "Infrastructure",
  },
  {
    id: 58,
    clientId: 12,
    date: "2024-03-08",
    amount: 350,
    type: "One-time",
    method: "Bank Transfer",
    category: "Events",
  },
  {
    id: 59,
    clientId: 12,
    date: "2024-04-18",
    amount: 400,
    type: "Monthly",
    method: "PayPal",
    category: "General",
  },
  {
    id: 60,
    clientId: 12,
    date: "2024-05-28",
    amount: 450,
    type: "One-time",
    method: "Credit Card",
    category: "Research",
  },

  // Donations for Client ID 13
  {
    id: 61,
    clientId: 13,
    date: "2024-01-19",
    amount: 150,
    type: "One-time",
    method: "Bank Transfer",
    category: "Events",
  },
  {
    id: 62,
    clientId: 13,
    date: "2024-02-09",
    amount: 350,
    type: "Monthly",
    method: "PayPal",
    category: "General",
  },
  {
    id: 63,
    clientId: 13,
    date: "2024-03-19",
    amount: 400,
    type: "One-time",
    method: "Credit Card",
    category: "Research",
  },
  {
    id: 64,
    clientId: 13,
    date: "2024-04-29",
    amount: 450,
    type: "Monthly",
    method: "Bank Transfer",
    category: "Infrastructure",
  },
  {
    id: 65,
    clientId: 13,
    date: "2024-05-09",
    amount: 500,
    type: "Yearly",
    method: "PayPal",
    category: "General",
  },

  // Donations for Client ID 14
  {
    id: 66,
    clientId: 14,
    date: "2024-01-23",
    amount: 500,
    type: "Yearly",
    method: "Credit Card",
    category: "Research",
  },
  {
    id: 67,
    clientId: 14,
    date: "2024-02-13",
    amount: 250,
    type: "One-time",
    method: "Bank Transfer",
    category: "Infrastructure",
  },
  {
    id: 68,
    clientId: 14,
    date: "2024-03-23",
    amount: 300,
    type: "Monthly",
    method: "PayPal",
    category: "Events",
  },
  {
    id: 69,
    clientId: 14,
    date: "2024-04-07",
    amount: 350,
    type: "One-time",
    method: "Credit Card",
    category: "General",
  },
  {
    id: 70,
    clientId: 14,
    date: "2024-05-17",
    amount: 400,
    type: "Monthly",
    method: "Bank Transfer",
    category: "Research",
  },

  // Donations for Client ID 15
  {
    id: 71,
    clientId: 15,
    date: "2024-01-29",
    amount: 300,
    type: "Monthly",
    method: "PayPal",
    category: "Events",
  },
  {
    id: 72,
    clientId: 15,
    date: "2024-02-19",
    amount: 450,
    type: "One-time",
    method: "Credit Card",
    category: "General",
  },
  {
    id: 73,
    clientId: 15,
    date: "2024-03-29",
    amount: 500,
    type: "Monthly",
    method: "Bank Transfer",
    category: "Research",
  },
  {
    id: 74,
    clientId: 15,
    date: "2024-04-12",
    amount: 550,
    type: "One-time",
    method: "PayPal",
    category: "Infrastructure",
  },
  {
    id: 75,
    clientId: 15,
    date: "2024-05-22",
    amount: 600,
    type: "Yearly",
    method: "Credit Card",
    category: "General",
  },

  // Donations for Client ID 16
  {
    id: 76,
    clientId: 16,
    date: "2024-01-04",
    amount: 200,
    type: "One-time",
    method: "Bank Transfer",
    category: "Research",
  },
  {
    id: 77,
    clientId: 16,
    date: "2024-02-14",
    amount: 500,
    type: "Yearly",
    method: "PayPal",
    category: "Infrastructure",
  },
  {
    id: 78,
    clientId: 16,
    date: "2024-03-24",
    amount: 350,
    type: "Monthly",
    method: "Credit Card",
    category: "Events",
  },
  {
    id: 79,
    clientId: 16,
    date: "2024-04-08",
    amount: 400,
    type: "One-time",
    method: "Bank Transfer",
    category: "General",
  },
  {
    id: 80,
    clientId: 16,
    date: "2024-05-18",
    amount: 450,
    type: "Monthly",
    method: "PayPal",
    category: "Research",
  },

  // Donations for Client ID 17
  {
    id: 81,
    clientId: 17,
    date: "2024-01-11",
    amount: 350,
    type: "Monthly",
    method: "Credit Card",
    category: "General",
  },
  {
    id: 82,
    clientId: 17,
    date: "2024-02-21",
    amount: 200,
    type: "One-time",
    method: "Bank Transfer",
    category: "Events",
  },
  {
    id: 83,
    clientId: 17,
    date: "2024-03-31",
    amount: 250,
    type: "Monthly",
    method: "PayPal",
    category: "Research",
  },
  {
    id: 84,
    clientId: 17,
    date: "2024-04-15",
    amount: 300,
    type: "One-time",
    method: "Credit Card",
    category: "Infrastructure",
  },
  {
    id: 85,
    clientId: 17,
    date: "2024-05-25",
    amount: 350,
    type: "Monthly",
    method: "Bank Transfer",
    category: "General",
  },

  // Donations for Client ID 18
  {
    id: 86,
    clientId: 18,
    date: "2024-01-21",
    amount: 400,
    type: "Monthly",
    method: "PayPal",
    category: "Research",
  },
  {
    id: 87,
    clientId: 18,
    date: "2024-02-11",
    amount: 600,
    type: "Yearly",
    method: "Credit Card",
    category: "Infrastructure",
  },
  {
    id: 88,
    clientId: 18,
    date: "2024-03-21",
    amount: 350,
    type: "One-time",
    method: "Bank Transfer",
    category: "Events",
  },
  {
    id: 89,
    clientId: 18,
    date: "2024-04-05",
    amount: 400,
    type: "Monthly",
    method: "PayPal",
    category: "General",
  },
  {
    id: 90,
    clientId: 18,
    date: "2024-05-15",
    amount: 450,
    type: "One-time",
    method: "Credit Card",
    category: "Research",
  },

  // Donations for Client ID 19
  {
    id: 91,
    clientId: 19,
    date: "2024-01-06",
    amount: 150,
    type: "One-time",
    method: "Bank Transfer",
    category: "Events",
  },
  {
    id: 92,
    clientId: 19,
    date: "2024-02-16",
    amount: 350,
    type: "Monthly",
    method: "PayPal",
    category: "General",
  },
  {
    id: 93,
    clientId: 19,
    date: "2024-03-26",
    amount: 400,
    type: "One-time",
    method: "Credit Card",
    category: "Research",
  },
  {
    id: 94,
    clientId: 19,
    date: "2024-04-10",
    amount: 450,
    type: "Monthly",
    method: "Bank Transfer",
    category: "Infrastructure",
  },
  {
    id: 95,
    clientId: 19,
    date: "2024-05-20",
    amount: 500,
    type: "Yearly",
    method: "PayPal",
    category: "General",
  },

  // Donations for Client ID 20
  {
    id: 96,
    clientId: 20,
    date: "2024-01-12",
    amount: 500,
    type: "Yearly",
    method: "Credit Card",
    category: "Research",
  },
  {
    id: 97,
    clientId: 20,
    date: "2024-02-22",
    amount: 250,
    type: "One-time",
    method: "Bank Transfer",
    category: "Infrastructure",
  },
  {
    id: 98,
    clientId: 20,
    date: "2024-03-12",
    amount: 300,
    type: "Monthly",
    method: "PayPal",
    category: "Events",
  },
  {
    id: 99,
    clientId: 20,
    date: "2024-04-22",
    amount: 350,
    type: "One-time",
    method: "Credit Card",
    category: "General",
  },
  {
    id: 100,
    clientId: 20,
    date: "2024-05-28",
    amount: 400,
    type: "Monthly",
    method: "Bank Transfer",
    category: "Research",
  },

  // Donations for Client ID 21
  {
    id: 101,
    clientId: 21,
    date: "2024-01-08",
    amount: 300,
    type: "Monthly",
    method: "PayPal",
    category: "Events",
  },
  {
    id: 102,
    clientId: 21,
    date: "2024-02-18",
    amount: 450,
    type: "One-time",
    method: "Credit Card",
    category: "General",
  },
  {
    id: 103,
    clientId: 21,
    date: "2024-03-28",
    amount: 500,
    type: "Monthly",
    method: "Bank Transfer",
    category: "Research",
  },
  {
    id: 104,
    clientId: 21,
    date: "2024-04-12",
    amount: 550,
    type: "One-time",
    method: "PayPal",
    category: "Infrastructure",
  },
  {
    id: 105,
    clientId: 21,
    date: "2024-05-22",
    amount: 600,
    type: "Yearly",
    method: "Credit Card",
    category: "General",
  },

  // Donations for Client ID 22
  {
    id: 106,
    clientId: 22,
    date: "2024-01-16",
    amount: 200,
    type: "One-time",
    method: "Bank Transfer",
    category: "Research",
  },
  {
    id: 107,
    clientId: 22,
    date: "2024-02-26",
    amount: 500,
    type: "Yearly",
    method: "PayPal",
    category: "Infrastructure",
  },
  {
    id: 108,
    clientId: 22,
    date: "2024-03-10",
    amount: 350,
    type: "Monthly",
    method: "Credit Card",
    category: "Events",
  },
  {
    id: 109,
    clientId: 22,
    date: "2024-04-20",
    amount: 400,
    type: "One-time",
    method: "Bank Transfer",
    category: "General",
  },
  {
    id: 110,
    clientId: 22,
    date: "2024-05-30",
    amount: 450,
    type: "Monthly",
    method: "PayPal",
    category: "Research",
  },

  // Donations for Client ID 23
  {
    id: 111,
    clientId: 23,
    date: "2024-01-24",
    amount: 350,
    type: "Monthly",
    method: "Credit Card",
    category: "General",
  },
  {
    id: 112,
    clientId: 23,
    date: "2024-02-14",
    amount: 200,
    type: "One-time",
    method: "Bank Transfer",
    category: "Events",
  },
  {
    id: 113,
    clientId: 23,
    date: "2024-03-24",
    amount: 250,
    type: "Monthly",
    method: "PayPal",
    category: "Research",
  },
  {
    id: 114,
    clientId: 23,
    date: "2024-04-08",
    amount: 300,
    type: "One-time",
    method: "Credit Card",
    category: "Infrastructure",
  },
  {
    id: 115,
    clientId: 23,
    date: "2024-05-18",
    amount: 350,
    type: "Monthly",
    method: "Bank Transfer",
    category: "General",
  },

  // Donations for Client ID 24
  {
    id: 116,
    clientId: 24,
    date: "2024-01-30",
    amount: 400,
    type: "Monthly",
    method: "PayPal",
    category: "Research",
  },
  {
    id: 117,
    clientId: 24,
    date: "2024-02-20",
    amount: 600,
    type: "Yearly",
    method: "Credit Card",
    category: "Infrastructure",
  },
  {
    id: 118,
    clientId: 24,
    date: "2024-03-30",
    amount: 350,
    type: "One-time",
    method: "Bank Transfer",
    category: "Events",
  },
  {
    id: 119,
    clientId: 24,
    date: "2024-04-14",
    amount: 400,
    type: "Monthly",
    method: "PayPal",
    category: "General",
  },
  {
    id: 120,
    clientId: 24,
    date: "2024-05-24",
    amount: 450,
    type: "One-time",
    method: "Credit Card",
    category: "Research",
  },

  // Donations for Client ID 25
  {
    id: 121,
    clientId: 25,
    date: "2024-01-09",
    amount: 150,
    type: "One-time",
    method: "Bank Transfer",
    category: "Events",
  },
  {
    id: 122,
    clientId: 25,
    date: "2024-02-19",
    amount: 350,
    type: "Monthly",
    method: "PayPal",
    category: "General",
  },
  {
    id: 123,
    clientId: 25,
    date: "2024-03-29",
    amount: 400,
    type: "One-time",
    method: "Credit Card",
    category: "Research",
  },
  {
    id: 124,
    clientId: 25,
    date: "2024-04-13",
    amount: 450,
    type: "Monthly",
    method: "Bank Transfer",
    category: "Infrastructure",
  },
  {
    id: 125,
    clientId: 25,
    date: "2024-05-23",
    amount: 500,
    type: "Yearly",
    method: "PayPal",
    category: "General",
  },
];
